sudo: false
latex: false
os:
  - linux
  - osx
compiler:
  - gcc
  #- clang  
  
matrix:
  allow_failures:
    - os: osx
    
dist: precise

language: r

cache: packages

r:
  - release
  
before_install:
  - export RGL_USE_NULL=TRUE;
  - export itkrrel=0.0.1
  - export gh_user=stnava
  - export ANTsRCorerel=0.2
  - export reldir=latest
  - export antsrrel=0.5.4
  - wget -O antsr_travis.sh http://bit.ly/antsr_travis_sh
  - chmod +x antsr_travis.sh
  - . ./antsr_travis.sh  
  - rm antsr_travis.sh
  - cat DESCRIPTION
  

