sudo: false
latex: false
warnings_are_errors: true
os:
  - linux
  - osx
compiler:
  - clang

matrix:
 allow_failures:
   - os: osx

dist: trusty

language: r

cache: packages

r:
  - release

before_install:
  - Rscript -e "install.packages(c('Rcpp', 'RcppEigen'), type = 'source', repos=c(CRAN='https://cran.rstudio.com'))"
  - wget -O antsr_travis.sh http://bit.ly/antsr_travis_sh
  - chmod +x antsr_travis.sh
  - . ./antsr_travis.sh
  - rm antsr_travis.sh
  - cat DESCRIPTION

